### ISSUE TITLE
Connecting Nodes on macOS doesn't work 

### ISSUE THREAD

**Issue by deflectn** [johannesvollmer/regex-nodes#1]
**OS**
macOS Mojave 10.14.4

**Browser**
Chrome 74.0.3729.131
Safari 12.1 (14607.1.40.1.4)
Firefox 66.0.5

moving nodes does work (LMB) but not connecting them (RMB)

no error is printed to the console

**Comment by johannesvollmer** [comment]
It's probably because on context menu is triggered on mouse down on MacOS, but on mouse up on Windows. Currently, context menu is not respected but only prevented, and MacOS does not trigger a separate mouse down event when pressing the second button.

**Comment by johannesvollmer** [comment]
@deflectn Please make sure this commit will fix your issue. Using BrowserStack, I tested connecting in Chrome and Firefox on MacOS Yosemite, and it worked.

**Comment by deflectn** [comment]
Now it works! Thanks Mr.
