### ISSUE TITLE
Zooming with continuous mouse wheels probably problematic

### ISSUE THREAD

**Issue by johannesvollmer** [johannesvollmer/regex-nodes#5]
Zoom has only been tested with discrete wheel events, and not with mouses which support fluid scrolling

**Comment by johannesvollmer** [comment]
Could be done while adding support for mobile devices.

**Comment by deflectn** [comment]
> Could be done while adding support for mobile devices.

*should

**Comment by johannesvollmer** [comment]
Should be improved now, the code looks better
